services:
  db:
    image: mysql:8.0
    container_name: ms-payment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_payment
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
volumes:
  mysqldb:
    external: true